### ISSUE TITLE
Put events in InfluxDB

### ISSUE THREAD

**Issue by skybarberom** [MountainGod2/chaturbate_poller#4]
Two possible way to enhance the project:

1- package the program in a container
2- Make it possible to insert events in a time-series DB, like Influx DB, to make some analysis / visualize data on Grafana to help understanding best time to cam / best tippers / etc.
This should be made with a configuration file that allow to select event destination

**Comment by MountainGod2** [comment]
Try out release v0.6.1 (928781d), and let me know what you think. I've also updated the docs with examples for the container.

I haven't tested out the example docker-compose.yml, but the docker run method seemed to work for me with my existing influxDB container on my server when I was testing.

I plan to eventually add a method to enable/disable the DB writing depending on arguments, but as of now, it is always on.

**Comment by skybarberom** [comment]
I've launched the docker with my variables for a test but I'm having a problem. Maybe I'm missing something:

```
2024-08-09 13:42:17 - INFO - Backing off 5.0 seconds after 1 tries
2024-08-09 13:42:23 - INFO - Backing off 6.2 seconds after 2 tries
2024-08-09 13:42:29 - INFO - Backing off 7.8 seconds after 3 tries
2024-08-09 13:42:38 - INFO - Backing off 9.8 seconds after 4 tries
2024-08-09 13:42:48 - INFO - Backing off 12.2 seconds after 5 tries
2024-08-09 13:43:01 - ERROR - Giving up after 6 tries
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/chaturbate_poller/__main__.py", line 80, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/chaturbate_poller/__main__.py", line 72, in main
    asyncio.run(
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chaturbate_poller/__main__.py", line 64, in start_polling
    response = await client.fetch_events(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chaturbate_poller/chaturbate_poller.py", line 139, in fetch_events
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://events.testbed.cb.dev/events/XXXXX/XXXXXXXXX/?timeout=10'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
```

I got a 500 error from the URL called (I masked user and token). 
I tried the https://eventsapi.chaturbate.com/events/  and     https://chaturbate.com/statsapi/   and they works ok

**Comment by MountainGod2** [comment]
Unfortunately, I think the testbed URL has been down for a couple days by the looks of it, as I've been getting the same 500 series errors when I try to pull up my testbed URL in my browser as well. It was working Tuesday when I rolled this patch out, so I'm hoping the get it back up and running in the next day or so. 

I should add some sanitation to the logs for the usernames and tokens in the log messages.

**Comment by MountainGod2** [comment]
I've updated the logging so that when `--verbose` is enabled, the username and token are sanitized from the `app.log` file in the mounted directory, and modified the `giveup_handler` function to log the error code/message instead of the full traceback.
```
2024-08-09 10:45:16 - DEBUG - chaturbate_poller - https://events.testbed.cb.dev/events/USERNAME/TOKEN/?timeout=10
2024-08-09 10:45:16 - INFO - chaturbate_poller - Backing off 5 seconds after 1 tries
2024-08-09 10:45:21 - DEBUG - chaturbate_poller - https://events.testbed.cb.dev/events/USERNAME/TOKEN/?timeout=10
2024-08-09 10:45:22 - INFO - chaturbate_poller - Backing off 6 seconds after 2 tries
2024-08-09 10:45:28 - DEBUG - chaturbate_poller - https://events.testbed.cb.dev/events/USERNAME/TOKEN/?timeout=10
2024-08-09 10:45:28 - INFO - chaturbate_poller - Backing off 7 seconds after 3 tries
2024-08-09 10:45:36 - DEBUG - chaturbate_poller - https://events.testbed.cb.dev/events/USERNAME/TOKEN/?timeout=10
2024-08-09 10:45:36 - INFO - chaturbate_poller - Backing off 9 seconds after 4 tries
2024-08-09 10:45:46 - DEBUG - chaturbate_poller - https://events.testbed.cb.dev/events/USERNAME/TOKEN/?timeout=10
2024-08-09 10:45:46 - INFO - chaturbate_poller - Backing off 12 seconds after 5 tries
2024-08-09 10:45:58 - DEBUG - chaturbate_poller - https://events.testbed.cb.dev/events/USERNAME/TOKEN/?timeout=10
2024-08-09 10:45:58 - ERROR - chaturbate_poller - Giving up after 6 tries due to server error code 500: An error occurred
```

Hopefully the testbed URL comes back online some time this weekend.
